{{ $os := .chezmoi.os }}
{{- if eq $os "darwin" }}
["Applications/Itsycal.app"]
type = "archive"
stripComponents = 1
refreshPeriod = "168h"
url = "https://itsycal.s3.amazonaws.com/Itsycal.zip"
{{- end }}

{{- range (gitHubLatestRelease "kak-lsp/kak-lsp").Assets }}
{{-   $asset := . }}
{{-   if contains $os $asset.Name }}
[".local/bin/kak-lsp"]
type = "file"
executable = true
url = "{{ $asset.BrowserDownloadURL }}"

[".local/bin/kak-lsp".filter]
command = "tar"
args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "kak-lsp"]
{{-     break }}
{{-   end }}
{{- end }}
